# Generated by Django 4.2 on 2023-05-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('asset_id', models.CharField(max_length=100)),
                ('system_type', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('imei_number', models.CharField(max_length=20)),
                ('dongle_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('filename', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
